# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: fullmonte software webpage
email: vtr-users@googlegroups.com
description: > # this means to ignore newlines until "baseurl:"
    Open source FullmonteSW
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fullmonteforPDT.org" # the base hostname & protocol for your site
logo: /img/vtr_logo.svg
github_username:  fullmonte-for-PDT

include: ["_pages"]

#Make urls succinct
permalink: /:title/

# Build settings
markdown: kramdown
gems:
    - jekyll-seo-tag
